#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const { transpile, ParseError } = require("../src/parser");

function usage() {
  console.log(`Spring compiler (springc)

Usage:
  springc <input.spring>              Print compiled JS to stdout
  springc <input.spring> -o <out.js>  Write compiled JS to a file
  springc --version                   Print version

Spring transpiles to plain JavaScript. Pair the output with
src/runtime.js in the browser to use text()/button()/stack().
`);
}

function main(argv) {
  const args = argv.slice(2);

  if (args.length === 0 || args.includes("-h") || args.includes("--help")) {
    usage();
    process.exit(args.length === 0 ? 1 : 0);
  }

  if (args.includes("--version")) {
    const pkg = require("../package.json");
    console.log(pkg.version);
    process.exit(0);
  }

  const inputPath = args[0];
  let outputPath = null;
  const oIndex = args.indexOf("-o");
  if (oIndex !== -1) outputPath = args[oIndex + 1];

  let source;
  try {
    source = fs.readFileSync(inputPath, "utf8");
  } catch (err) {
    console.error(`springc: cannot read "${inputPath}": ${err.message}`);
    process.exit(1);
  }

  let js;
  try {
    js = transpile(source);
  } catch (err) {
    if (err instanceof ParseError) {
      console.error(`springc: ${err.message}`);
      console.error(`  in ${inputPath}`);
      process.exit(1);
    }
    throw err;
  }

  const banner = `// Generated by springc from ${path.basename(inputPath)} -- do not edit by hand.\n`;
  const output = banner + js + "\n";

  if (outputPath) {
    fs.writeFileSync(outputPath, output, "utf8");
    console.log(`springc: wrote ${outputPath}`);
  } else {
    process.stdout.write(output);
  }
}

main(process.argv);
